fifth_task
pigchevalier/test-guru pull request #5
Opened 2021-12-01 14:14 UTC by pigchevalier

2021-12-01 15:55 UTC, VidgarVii commented on app/models/question.rb
> +  end
валидация в модели Вопрос не будет препятствовать созданию новых ответов в количестве больше 4, потому что она не будет вызываться при добавлении новых ответов к вопросу

валидации в классе Вопрос вызываются при создании или изменении объектов класса Вопрос
при создании объектов класса Ответ валидации в классе Вопрос не вызываются

видимо данная валидации не тестировалась

2021-12-01 15:55 UTC, VidgarVii commented on app/models/test.rb
> +                                                  .pluck(:title) }
у скоупов есть важная особенность - они должны возвращать chainable объекты (объекты `ActiveRecord::Relation`)
благодаря этому с их использованием можно строить цепочки вызовов
скоупы можно чейнить с квери-методами  `ActiveRecord`, к примеру `where(level: ...).order(id: :desc).created_last_week ...`, с методами ассоциаций
квери-методы также возвращают объекты `ActiveRecord::Relation`
НО!
`pluck` вернет обычный массив, что нарушит эту конвенцию
поэтому, если скоуп должен вернуть объект или массив, но не `ActiveRecord::Relation`, то его лучше реализовывать обычными методами класса

здесь можно создать скоуп, который будет делать, к примеру, все кроме `pluck`
а при желании сохранить прежнюю функциональность можно оставить плюс к скоупу метод класса и уже в методе класса (из прошлого задания) убрать все запросы, вызвать этот скоуп и зачейнить его "плаком"

2021-12-01 15:55 UTC, VidgarVii commented on app/models/test.rb
> +                                                  .pluck(:title) }
и по сразу по синтаксису. При много строчных блоках используют do end, а не {}
и скоупы лучше делать максимально простыми. В идеале чтобы код влезал в 1 строку. Но это не обязательно.  Я бы вообще этот метод класса не трог

2021-12-01 15:55 UTC, VidgarVii commented on app/models/user.rb
> +  #поскольку это инстанс метод, а не метод класса, он не переделывается в scope
Хорошо) коммент можно удалить)

2021-12-01 15:55 UTC, VidgarVii commented on config/locales/ru.yml
> +en:
этот файл отвечает за русскую локализацию

2021-12-01 19:02 UTC, pigchevalier commented on app/models/question.rb
> +  end
Тестировалась, но я здесь запуталась и использовала её только для проверки .validate?

2021-12-02 08:43 UTC, VidgarVii requested changes

2021-12-02 08:43 UTC, VidgarVii commented on app/models/answer.rb
> +    errors.add(:question) if question.id_changed? && question.answers.count <= 1
1 валидацию на минимальное количество лучше не делать, потому что текущий вариант не позволит тебе создавать ответы к вопросу
а правильный вариант на минимальное количество может сильно усложнить наше учебное приложение
2 Такого кейса где требовалось бы проверять смену ид вопроса, точно не будет

2021-12-02 08:43 UTC, VidgarVii commented on app/models/answer.rb
> +  validate :validate_min_count_of_answers, on: :update
согласно ДЗ нужна только 1 валидация. 
Проверять кол-во ответов у вопроса. Надо только при создании ответа. Как раз при обновлении ответа, если ответов уже 4 - будут баги

2021-12-02 08:43 UTC, VidgarVii commented on app/models/question.rb
> +  end
зачем нам нужен этот код, если он даже не выполняет поставленную задачу?

2021-12-02 08:43 UTC, VidgarVii commented on app/models/question.rb
> +  end
тестировать надо созданием ответов.

2021-12-02 16:55 UTC, VidgarVii commented on app/models/answer.rb
> +  validate :validate_max_count_of_answers_create
https://github.com/pigchevalier/test-guru/pull/5#discussion_r760869319

2021-12-02 17:05 UTC, merged