ninth task
pigchevalier/test-guru pull request #9
Opened 2021-12-07 22:56 UTC by pigchevalier

2021-12-08 08:35 UTC, VidgarVii requested changes

2021-12-08 08:35 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +      cookies[:path] = request.path
Очень слабое название. По нему сложно понять что содержит ключ и зачем. В проекте может быть много кук. Потом легко можно будет запутаться кто за что отвечает.

2021-12-08 08:35 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:path]
а если нет такой записи? То будет ошибка
Если записи нет. То надо редиректить юзера на дефолтную страницу

2021-12-08 08:35 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      cookies.delete :path
cookies.delete :path еще вернёт значение path. Используй это сразу в redirect_to

2021-12-08 08:35 UTC, VidgarVii commented on app/helpers/flash_helper.rb
> +  #я не поняла что именно требуется в задании "Создайте хэлпер для flash сообщений"
создать метод который будет возвращать хтмл для флеш сообщения определённого типа
Пример чтобы можно было вызвать во вью
 = flash_message(:notice)
И этот метод вернул сообщение в хтмл + нужные css классы для этого флеш 
как link_to возвращает хтмл для ссылки

2021-12-08 08:35 UTC, VidgarVii commented on app/models/user.rb
> +  validates :email, uniqueness: true, presence: true, format: { with: /.+[@].+[.].+/, message: "only email allows"}
еще один вариант - использовать доступную в библиотеках ruby регулярку для email - она доступна вот так: `URI::MailTo::EMAIL_REGEXP` (можешь посмотреть в консоли)

2021-12-08 08:36 UTC, VidgarVii requested changes

2021-12-08 08:36 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @user = User.find(session[:user_id])
зачем?) у тебя ведь есть метод current_user. Его же надо использовать в экшане создания теста

2021-12-08 08:38 UTC, VidgarVii requested changes

2021-12-08 08:38 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :authenticate_user!
как то маловато. А над работой с вопросами и ответами имеет доступ любой юзер?

2021-12-08 15:24 UTC, VidgarVii requested changes

2021-12-08 15:24 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      end
нет смысла обрабатывать ошибки, когда можно их не допускать. Raise это всегда долго работает.
`redirect_to cookies.delete(:path_after_login) || root_path`
И не нужны ни какие rescue

2021-12-08 15:24 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +    session.delete(:user_id)
сессию надо удалять до редиректа.
Воспринимай redirect_to как return
Всё что ниже - не работает

2021-12-08 15:24 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
для чего каждый раз писать и перезаписывать почту юзера? Она даже не используется
Такое ощущение, что у друг друга списываете не разбирая код =(
Этот метод нужен только для того чтобы не залогиненного юзера не пускать далее

2021-12-08 15:24 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @user = current_user
что делает метод current_user? Возвращает текущего юзера
Что делает переменная @user????  Возвращает текущего юзера
Зачем нам нужна переменная @user если есть current_user????????

2021-12-08 15:24 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @user = current_user
при создании теста надо так же использовать current_user для установки автора

2021-12-08 15:24 UTC, VidgarVii commented on app/helpers/flash_helper.rb
> +    content_tag :div, msg, class: "flash #{type}"
объект flash так же доступен во хелперах.
Можно не передавть msg в метод. А сразу обращаться к flash внутри метода

2021-12-08 15:24 UTC, VidgarVii commented on app/views/sessions/_form.html.erb
> +  <% end %>
вот тут можно было вызвать хелпер для показа flash

2021-12-08 15:43 UTC, pigchevalier commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
этот код был представлен в теории (в видео), соответственно откуда и брала этот код

2021-12-08 15:45 UTC, pigchevalier commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
эта почта используется для идентификации пользователя, а так же как его "имя", по крайней мере так было сделано в видео - теории, и соответственно при выполнении задания, я опираюсь на ту теорию которая дана в этом уроке

2021-12-08 15:59 UTC, pigchevalier commented on app/controllers/sessions_controller.rb
> +    session.delete(:user_id)
в видео flash-сообщения на 12 минуте говорится, наоборот, что код после redirect_to продолжает выполняться и если надо сделать так чтоб он не выполнялся, надо использовать return redirect_to

2021-12-09 08:18 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +    session.delete(:user_id)
да или пишут еще так 
redirect_to ... and return
В общем эта штука сильно запутывает. И хоршим кейсом будет когда redirect_to или render стоит в самом конце метода

2021-12-09 08:54 UTC, merged